# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/tttest20221008',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/tttest20221008',
                'lib_path': 'tttest20221008'},
  'syms': {'tttest20221008.core': {'tttest20221008.core.foo': ('core.html#foo', 'tttest20221008/core.py')}}}